### ISSUE TITLE
Include german language

### ISSUE THREAD

**Issue by flocomkoko** [Jason-Rev/vscode-spell-checker#119]
Is was wondering if it would be possible to include more languages in the standard configuration? The dictionaries are there, it would be just a matter of packaging them. 
I am using vs code as a LaTeX editor and a good german spell checking is just what i am missing.

**Comment by Jason3S** [comment]
Try this: https://www.npmjs.com/package/cspell-dict-de-de

You will need to tell the spell checker to use it:
In your project settings:
```
"cspell.language": "en,de"
```

or in cSpell.json file:
```
"language": "en,de"
```

**Comment by flocomkoko** [comment]
Thank you, for your fast response.
Sadly i am not familiar with nodejs or javascript development and i am sure many other people would be pleased if you could include common dictionarys (french, russian, german, spanish e.g.) by default in the extension.
I don't think it would increase the size of this nice piece of software too much and it would be a great addition for writing markdown/LaTeX files.

**Comment by d2s** [comment]
@flocomkoko Including a basic German dictionary would increase the size of extension by at least 4 MB, so that generally might not make sense to do by default.

- [cspell-dicts](https://github.com/Jason3S/cspell-dicts/tree/master/de_DE) repository shows what things there are in the German dictionary.

Node.js & tools distributed via npm can be installed easily,
without need to know anything about JavaScript itself.
- Quick guide: [Installing Node.js with nvm to Linux & OS X](https://gist.github.com/d2s/372b5943bce17b964a79)

After installing the Node itself, run these two commands in your computer's command line terminal:
```
npm install -g cspell-dict-de-de
```
```
cspell-dict-de-de-link
```

After that, follow the instructions of the [Spell Checker's documentation](https://github.com/Jason-Rev/vscode-spell-checker/blob/master/client/README.md#customization). You can either add the settings to VS Code's global settings, or have project-specific custom adjustments.

**Comment by flocomkoko** [comment]
Oh, i see. 
Now it works very well on my end, 4 MB would be indeed too much. 
Thank you for your help.

**Comment by Jason3S** [comment]
You still bring up a good point. I am looking into making VS Code add-on extensions for each of the common languages. This would make installing them much easier.

**Comment by flocomkoko** [comment]
That would be a really nice and easy solution.
