### ISSUE TITLE
German language pack

### ISSUE THREAD

**Issue by flocomkoko** [Jason-Rev/vscode-spell-checker#132]
Since now Dutch, Russian, Swedish and Spanish language extensions have landed in the store, i would really appreciate if you could add a german extensions, that simplifies the setup.

**Comment by Jason3S** [comment]
Good idea. I didn't add it yet because it only half supports German word compounds. There is some work necessary to correctly support connecting words together. At the moment, it considers any two words (English or German) connected together to be correct. Which means some clearly incorrect words are considered correct.

I can add it in preview mode until I get the compounding rules supported by hunspell working.

**Comment by flocomkoko** [comment]
That would be really nice.

**Comment by Jason3S** [comment]
Here you go: [German Spell Checker](https://marketplace.visualstudio.com/items?itemName=streetsidesoftware.code-spell-checker-german)

Please let me know if you have any issues.
