### ISSUE TITLE
Empty Language Setting Causes False Misspellings

### ISSUE THREAD

**Issue by ctsstc** [Jason-Rev/vscode-spell-checker#139]
I noticed I had a lot of words coming through that were not being recognized as being spelled correctly.

I dug around in my settings and found that there was an empty string set for the language which seems to have been causing the problems.

This is the settings value that breaks the spelling.

```
"cSpell.language": ""
```

**Comment by Jason3S** [comment]
Thank you. I can see how that would be hard to track down and figure out.

If you delete the entry from the `settings.json` file you will get the defaults.

What happens if you right click in the editor and choose:
![image](https://user-images.githubusercontent.com/3740137/30800013-f161acbe-a1de-11e7-85e4-60f8c5576232.png)

If all the switches are turned off, then the `cSpell.language` will be `""`.

**Comment by Jason3S** [comment]
I'm working on a fix for this case.

**Comment by Jason3S** [comment]
Please re-open if this is still an issue.
