### ISSUE TITLE
Can't find out typo 'recommend' in Go

### ISSUE THREAD

**Issue by ghost** [Jason-Rev/vscode-spell-checker#147]
When file ended ".go" ext, a typo "recommend" to "reccomend" was not detected as a "Unknown Word", Although other file type,  such as plain text, works correct.

**Comment by Jason3S** [comment]
Hello @ginshari,

This is an issue with `allowCompoundWords` setting. It will put any words together. Because many "go" libraries compound words like: `IPv6interfacelocalallnodes`. Since the newer libaries seem to follow camelCase, it might be worth it to turn off the `allowCompoundWords` setting by default for GO.

**Comment by Jason3S** [comment]
Closing this for now.
