### ISSUE TITLE
dictionary for RU

### ISSUE THREAD

**Issue by wBureshGitHub** [Jason-Rev/vscode-spell-checker#81]
Awesome! Very nice work!
I added dictionary for RU (more then 1m words  (one word on one  line) in one file in .dict format). Works very fast!
So very easy to add new words in my own dictionary by copying from Spell Checker Information Issues.

Settings (Linux, Debian, Stretch):

`"CSpell.dictionaryDefinitions": [

     {"Name": "dicRU", "path": "/home/.../dicts/dicRU.dict"}
],

"CSpell.dictionaries": [

    "DicRU"
]`

I mast do my work today. And I do it!
Big THANKS!

I tried to compile the dictionary for RU with cSpell-Tools.
But I was able to just install the cspell-tools npm package:

`$ npm -g list --depth=0

/usr/lib

├── cspell-tools@1.3.2`

When I try to run the Cspell-tools --help command in a terminal
The terminal stops responding. The same with other terminal commands for Cspell-tools.
_Dictionaries are from:  Hunspell UTF8 dictionaries_ [https://github.com/titoBouzout/Dictionaries
](url)

Help me please.

Thank You!

**Comment by Jason3S** [comment]
Hello wb,

It is great that you tried.

Adding the .dic file directly to `CSpell.dictionaryDefinitions` will only give you the base words, but not all of the word forms.

To compile all the word forms, we need to convert the *.dic* file into a *.trie* file.  I generally use [cspell-tools](https://github.com/Jason3S/cSpell-Tools) to create dictionary files for use with the spell checker.

A couple of months ago, I tried compiling the *Russian* dictionary.  I ran into a performance issue due to how the rules are defined in the *.aff* file.  The way the rules are setup, causes the same word to be generated many times.  I think it is possible to generate the file, but it will take a very long time (many hours).  I was working on a fix to speed it up, but I hadn't the time to finish it.

I'll give it another try.

When I get it working, I'll add it here: [cspell-dicts](https://github.com/Jason3S/cspell-dicts).

Cheers,
Jason

**Comment by Jason3S** [comment]
I ended up using a different Hunspell dictionary because it compiled much faster:
[ru_RU](https://github.com/Jason3S/cspell-dicts/tree/master/ru_RU)

**Comment by wBureshGitHub** [comment]
Excellent. Very snappy! 

I immediately start testing and using.

Immensely grateful to you for your responsiveness and diligence. It made our life much easy and better ))

Sincerely,
Vladimir Buresh

**Comment by wBureshGitHub** [comment]
I installed NPM packages on two computers in different projects. After the required settings, the application started working fine!
Big thanks!

**Comment by Jason3S** [comment]
Hello Vladimir,

I am glad it worked.  The other Russian dictionary finished compiling.
You can find it here: https://www.npmjs.com/package/cspell-dict-russian

Cheers,
Jason

**Comment by wBureshGitHub** [comment]
Excellent, this dictionary is much better. I installing it rigth now.

With respect,
Vladimir

**Comment by Jason3S** [comment]
I'm glad you found it useful.
